homeassistant:

####################################################
#                                                  #
#             Entidades Dummies                    #
#                                                  #
####################################################

####################################################
#                                                  #
#             Segunda Planta                       #
#                                                  #
####################################################
switch:
  - platform: demo