homeassistant:
  name: STALYN QUISHPE
  latitude: -0.3263547
  longitude: -78.5358156
  unit_system: metric
  time_zone: America/Guayaquil
  customize_glob:
    "cover.*":
      assumed_state: true
  packages:
    pack_1: !include_dir_merge_named ismart/config/
    pack_2: !include_dir_merge_named ismart/servicios/
    pack_3: !include_dir_merge_named ismart/integraciones/
frontend:
  development_repo: /share/frontend
  themes: !include_dir_merge_named themes
automation generales: !include_dir_list ismart/automatizaciones/generales/
automation principal: !include_dir_list /ismart/principal/
automation ui: !include automations.yaml
scene: !include_dir_merge_list ismart/scenes/
lovelace:
  mode: storage
  dashboards:
    lovelace-yaml-optimized:
      mode: yaml
      title: FloorPlan
      icon: mdi:home
      show_in_sidebar: True
      filename: www/ismart/planos/plano-main.yaml
http:
  use_x_forwarded_for: True
  trusted_proxies: ['172.30.33.0/24']
  ip_ban_enabled: True
  login_attempts_threshold: 5
default_config: 
demo: 
tts: [{'platform': 'google_translate'}]
script: !include scripts.yaml
switch luces_interior: !include_dir_merge_list ismart/principal/Zonas/Interior/Integraciones/grupos/switch/
switch luces_interior_segunda_planta: !include_dir_merge_list ismart/principal/Zonas/Interior/Ubicacion/Segunda-planta/Integraciones/grupos/switch/
switch luces_interior_segunda_planta_estudio: !include_dir_merge_list ismart/principal/Zonas/Interior/Ubicacion/Segunda-planta/Areas/Estudio/Integraciones/grupos/switch/
sensor temperatura_interior: !include_dir_merge_list ismart/principal/Zonas/Interior/Integraciones/grupos/Temperatura/
sensor temperatura_segunda_planta: !include_dir_merge_list ismart/principal/Zonas/Interior/Ubicacion/Segunda-planta/Integraciones/grupos/Temperatura/
sensor temperatura_sala: !include_dir_merge_list ismart/principal/Zonas/Interior/Ubicacion/Segunda-planta/Areas/Sala/Integraciones/grupos/Temperatura/
sensor humedad_interior: !include_dir_merge_list ismart/principal/Zonas/Interior/Integraciones/grupos/Humedad/
sensor humedad_segunda_planta: !include_dir_merge_list ismart/principal/Zonas/Interior/Ubicacion/Segunda-planta/Integraciones/grupos/Humedad/
sensor humedad_sala: !include_dir_merge_list ismart/principal/Zonas/Interior/Ubicacion/Segunda-planta/Areas/Sala/Integraciones/grupos/Humedad/
cover cortinas_interior: !include_dir_merge_list ismart/principal/Zonas/Interior/Integraciones/grupos/Cortinas/
cover cortinas_segunda_planta: !include_dir_merge_list ismart/principal/Zonas/Interior/Ubicacion/Segunda-planta/Integraciones/grupos/Cortinas/
cover cortinas_estudio: !include_dir_merge_list ismart/principal/Zonas/Interior/Ubicacion/Segunda-planta/Areas/Estudio/Integraciones/grupos/Cortinas/
