
 ######   ########  ##     ## ########   #######   ######     ########  ######## ##     ##  #######  
##    ##  ##     ## ##     ## ##     ## ##     ## ##    ##    ##     ## ##       ###   ### ##     ## 
##        ##     ## ##     ## ##     ## ##     ## ##          ##     ## ##       #### #### ##     ## 
##   #### ########  ##     ## ########  ##     ##  ######     ##     ## ######   ## ### ## ##     ## 
##    ##  ##   ##   ##     ## ##        ##     ##       ##    ##     ## ##       ##     ## ##     ## 
##    ##  ##    ##  ##     ## ##        ##     ## ##    ##    ##     ## ##       ##     ## ##     ## 
 ######   ##     ##  #######  ##         #######   ######     ########  ######## ##     ##  #######  

# Example configuration.yaml entry
switch:
- platform: group
  name: grupo_demo_switch
  entities:
    - switch.ac
    - switch.decorative_lights
    

    