alias: Git Push Configuraciones
id: 0add387f-5d27-40ff-825d-8f9723e7a581
description: "Enviar la_configuracion a github a cierta hora"
trigger:
  - platform: time
    at: "01:00:00"
action:
  - service: shell_command.push_to_github
condition: []
mode: single