alias: Desactivar emparejamiento Zigbee por tiempo
id: 86e350f0-f338-4404-b058-ddc7256c62d2
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee_permitir_join
action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'false'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.zigbee_permit_join
condition: []
mode: single