homeassistant: true
permit_join: false
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: xusa0zainoob2noo7ahl0pohGh9ahkaapah2Jae2xah0vae3Ik3aegheobeida1i
serial:
  port: /dev/ttyACM0
frontend:
  port: 8099
advanced:
  pan_id: 52409
  channel: 11
  network_key:
    - 192
    - 26
    - 101
    - 146
    - 145
    - 163
    - 19
    - 113
    - 174
    - 57
    - 48
    - 118
    - 5
    - 217
    - 64
    - 113
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_level: info
device_options:
  legacy: false
devices:
  '0x00124b002263095a':
    friendly_name: interruptor_simple_techo_luz_00_zigbee_01_interior_estudio
  '0xf4b3b1fffef8ad53':
    friendly_name: motor_cortina_pared_m_cortina_00_zigbee_01_interior_estudio
  '0x00124b0025143350':
    friendly_name: Sensor Humedad temperatura Sala
