- platform: group
  type: mean
  name: temperatura_segunda_planta
  unique_id: group_sensor_temperatura_segunda-planta
  entities:
  - sensor.sensor_pared_temperatura_02_zigbee_01_interior_sala
